/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoclaudiohernandez_programacion2;

import jaco.mp3.player.MP3Player;
import java.awt.Dimension;
import java.awt.Font;
import java.io.File;
import java.nio.file.Paths;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.FloatControl;
import javax.sound.sampled.Line;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.Mixer;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Majey
 */
public class PlayerFrame extends javax.swing.JFrame {

    /**
     * Creates new form PlayerFrame
     */
    // creo clase MP3Player de JACO MP3Player el que importe
    MP3Player player;
    // Hago un file para la cancion
    File songFile;
    // creo un directorio actual
    String currentDirectory = "home.user"; // llamo al  file chooser en user documents.
    // defino ruta de la aplicacion
    String currentPath;

    // We need to set app title as string
    String appName = "Reproductor de Musica";

    // Now Check If Repeat Button is Enabled or not
    boolean repeat = false;

    // Here I am making a boolean for windowCollapsed
    boolean windowCollapsed = false;

    // Here I need to define mouse x and y for to get mouse position on screen.
    int xMouse, yMouse;

    public PlayerFrame() {
        initComponents();
        // le pongo el titulo , no es necesario ponerlo si a lo defini
        tituloReproductor.setText(appName);
        // dejo una ruta predeterminada
        songFile = new File("E:\\New-Data-From-Sony\\Music-Downloads\\GamePlayMusic.mp3");

        // Hago un  string para ell nombre del file
       String fileName = songFile.getName();
        // pongo el nombre de cancion, al inicar siempre sera esto
        textNombreCancion.setText("SIN MUSICA SELECCIONADA");

        // mando el metodo a player
        player = mp3Player();
        // agrego cancion a player  como.
        player.addToPlayList(songFile);

        // tomo como String la ruta
        currentPath = Paths.get(".").toAbsolutePath().normalize().toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelfondotodo = new javax.swing.JPanel();
        panelTitulo = new javax.swing.JPanel();
        tituloReproductor = new javax.swing.JLabel();
        salir = new javax.swing.JLabel();
        songNameMainPanel = new javax.swing.JPanel();
        panelDebajoNombre = new javax.swing.JPanel();
        textNombreCancion = new javax.swing.JLabel();
        controlPanel = new javax.swing.JPanel();
        botonPausar = new javax.swing.JLabel();
        botonPlay = new javax.swing.JLabel();
        Buscar = new javax.swing.JLabel();
        FondoAnimado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        panelfondotodo.setBackground(new java.awt.Color(0, 0, 0));

        panelTitulo.setBackground(new java.awt.Color(0, 0, 0));

        tituloReproductor.setBackground(new java.awt.Color(0, 153, 51));
        tituloReproductor.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        tituloReproductor.setForeground(new java.awt.Color(255, 255, 255));
        tituloReproductor.setText("reproductor");
        tituloReproductor.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                tituloReproductorMouseDragged(evt);
            }
        });
        tituloReproductor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tituloReproductorMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tituloReproductorMousePressed(evt);
            }
        });

        salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoclaudiohernandez_programacion2/sonido/equis.jpg"))); // NOI18N
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloReproductor, javax.swing.GroupLayout.DEFAULT_SIZE, 876, Short.MAX_VALUE)
                .addGap(62, 62, 62)
                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(salir, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
            .addComponent(tituloReproductor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        songNameMainPanel.setBackground(new java.awt.Color(0, 0, 0));

        panelDebajoNombre.setBackground(new java.awt.Color(0, 0, 0));
        panelDebajoNombre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 153), 1, true));

        textNombreCancion.setBackground(new java.awt.Color(204, 255, 51));
        textNombreCancion.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        textNombreCancion.setForeground(new java.awt.Color(153, 0, 153));
        textNombreCancion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textNombreCancion.setText("PLAYING");

        javax.swing.GroupLayout panelDebajoNombreLayout = new javax.swing.GroupLayout(panelDebajoNombre);
        panelDebajoNombre.setLayout(panelDebajoNombreLayout);
        panelDebajoNombreLayout.setHorizontalGroup(
            panelDebajoNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textNombreCancion, javax.swing.GroupLayout.DEFAULT_SIZE, 974, Short.MAX_VALUE)
        );
        panelDebajoNombreLayout.setVerticalGroup(
            panelDebajoNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textNombreCancion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        controlPanel.setBackground(new java.awt.Color(0, 0, 0));

        botonPausar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botonPausar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoclaudiohernandez_programacion2/sonido/pausa1.jpg"))); // NOI18N
        botonPausar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonPausarMouseClicked(evt);
            }
        });

        botonPlay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botonPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoclaudiohernandez_programacion2/sonido/playajja.jpg"))); // NOI18N
        botonPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonPlayMouseClicked(evt);
            }
        });

        Buscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoclaudiohernandez_programacion2/sonido/sacar.jpg"))); // NOI18N
        Buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(botonPausar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124)
                .addComponent(botonPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117)
                .addComponent(Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonPausar, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(botonPlay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        FondoAnimado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoclaudiohernandez_programacion2/sonido/hhhhh.gif"))); // NOI18N

        javax.swing.GroupLayout songNameMainPanelLayout = new javax.swing.GroupLayout(songNameMainPanel);
        songNameMainPanel.setLayout(songNameMainPanelLayout);
        songNameMainPanelLayout.setHorizontalGroup(
            songNameMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(songNameMainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDebajoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(controlPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, songNameMainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(FondoAnimado, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(319, 319, 319))
        );
        songNameMainPanelLayout.setVerticalGroup(
            songNameMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(songNameMainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDebajoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(controlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FondoAnimado, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelfondotodoLayout = new javax.swing.GroupLayout(panelfondotodo);
        panelfondotodo.setLayout(panelfondotodoLayout);
        panelfondotodoLayout.setHorizontalGroup(
            panelfondotodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(songNameMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelfondotodoLayout.setVerticalGroup(
            panelfondotodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelfondotodoLayout.createSequentialGroup()
                .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(songNameMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(panelfondotodo, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonPlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonPlayMouseClicked
        // TODO add your handling code here:
        player.play();
    }//GEN-LAST:event_botonPlayMouseClicked

    private void botonPausarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonPausarMouseClicked
        // TODO add your handling code here:
        player.pause();
    }//GEN-LAST:event_botonPausarMouseClicked

    private void tituloReproductorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tituloReproductorMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_tituloReproductorMousePressed

    private void tituloReproductorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tituloReproductorMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_tituloReproductorMouseDragged

    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked
        // TODO add your handling code here:
        player.stop();
        this.dispose();
    }//GEN-LAST:event_salirMouseClicked

    private void BuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarMouseClicked
        // TODO add your handling code here:
        JFileChooser openFileChooser = new JFileChooser(currentDirectory);
        openFileChooser.setFileFilter(new FileTypeFilter(".mp3", "Open MP3 Files Only!"));
        int result = openFileChooser.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            songFile = openFileChooser.getSelectedFile();
            player.addToPlayList(songFile);
            player.skipForward();
            currentDirectory = songFile.getAbsolutePath();
            textNombreCancion.setText("Reproduciendo...| " + songFile.getName());
        }
    }//GEN-LAST:event_BuscarMouseClicked

    private void tituloReproductorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tituloReproductorMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            if (windowCollapsed == false) {
                windowCollapsed = true;
                this.setSize(new Dimension(this.getSize().width, 50));

                tituloReproductor.setFont(new Font("Nirmala UI", 0, 12));
                tituloReproductor.setText("Reproduciendo... | " + songFile.getName());
            } else if (windowCollapsed == true) {
                windowCollapsed = false;
                this.setSize(new Dimension(this.getSize().width, 250));

                tituloReproductor.setFont(new Font("Nirmala UI", 0, 18));
                tituloReproductor.setText(appName);
            }
        }
    }//GEN-LAST:event_tituloReproductorMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Buscar;
    private javax.swing.JLabel FondoAnimado;
    private javax.swing.JLabel botonPausar;
    private javax.swing.JLabel botonPlay;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JPanel panelDebajoNombre;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JPanel panelfondotodo;
    private javax.swing.JLabel salir;
    private javax.swing.JPanel songNameMainPanel;
    private javax.swing.JLabel textNombreCancion;
    private javax.swing.JLabel tituloReproductor;
    // End of variables declaration//GEN-END:variables

    // creo metodo para mandar a player 
    private MP3Player mp3Player() {
        MP3Player mp3Player = new MP3Player();
        return mp3Player;
    }

}
